// filename: CreateProjectForm.jsx
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { useContext, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import Sidebar from '../components/Sidebar';
import { createProject, getProjectsByOwner } from '../services/projectService';
import { getAllIssues } from '../services/issueService';

function CreateProjectForm() {
    const { user, isLoggedIn } = useContext(AuthContext);
    const navigate = useNavigate();

    const nameRef = useRef();
    const startRef = useRef();
    const endRef = useRef();

    const [errors, setErrors] = useState({});
    const [serverError, setServerError] = useState('');
    const [projectsCount, setProjectsCount] = useState(0);
    const [createdIssueCount, setCreatedIssueCount] = useState(0);

    useEffect(() => {
        if (!isLoggedIn || Number(user?.role) !== 1) {
            return;
        }

        const loadCounts = async () => {
            try {
                const [projectData, allIssues] = await Promise.all([
                    getProjectsByOwner(user.userId),
                    getAllIssues()
                ]);

                setProjectsCount(projectData.length);
                setCreatedIssueCount(
                    allIssues.filter(
                        (issue) => Number(issue.createdBy) === Number(user.userId)
                    ).length
                );
            } catch {
                setProjectsCount(0);
                setCreatedIssueCount(0);
            }
        };

        loadCounts();
    }, [isLoggedIn, user?.userId, user?.role]);

    const validate = (projectName, startDate, endDate) => {
        const next = {};

        if (!projectName) {
            next.projectName = 'Project name is required.';
        }

        if (startDate && endDate && endDate < startDate) {
            next.endDate = 'End date cannot be before start date.';
        }

        return next;
    };

    const handleSubmit = async (event) => {
        event.preventDefault();

        const projectName = nameRef.current.value.trim();
        const startDate = startRef.current.value;
        const endDate = endRef.current.value;

        const validationErrors = validate(projectName, startDate, endDate);
        setErrors(validationErrors);

        if (Object.keys(validationErrors).length > 0) {
            return;
        }

        try {
            await createProject({
                projectName,
                projectOwner: user.userId,
                startDate: startDate || null,
                endDate: endDate || null
            });

            navigate('/project-dashboard');
        } catch (error) {
            setServerError(
                error.response?.data?.message || 'Unable to create project.'
            );
        }
    };

    if (!isLoggedIn || Number(user?.role) !== 1) {
        return null;
    }

    return (
        <div className="case-dashboard">
            <Sidebar projectsCount={projectsCount} issuesCount={createdIssueCount} />

            <main className="case-main">
                <div className="case-form-card">
                    <div className="case-title-bar">Issue Tracking System</div>
                    <div className="p-4">
                        <h3>Create Project</h3>

                        {serverError && (
                            <div className="alert alert-danger">{serverError}</div>
                        )}

                        <form onSubmit={handleSubmit} noValidate>
                            <div className="mb-3">
                                <label className="form-label">Project Name</label>
                                <input
                                    type="text"
                                    name="projectName"
                                    ref={nameRef}
                                    defaultValue=""
                                    className={`form-control ${errors.projectName ? 'is-invalid' : ''}`}
                                />
                                {errors.projectName && (
                                    <div className="invalid-feedback">{errors.projectName}</div>
                                )}
                            </div>

                            <div className="row">
                                <div className="col-md-6 mb-3">
                                    <label className="form-label">Start Date</label>
                                    <input
                                        type="date"
                                        name="startDate"
                                        ref={startRef}
                                        defaultValue=""
                                        className="form-control"
                                    />
                                </div>

                                <div className="col-md-6 mb-3">
                                    <label className="form-label">End Date</label>
                                    <input
                                        type="date"
                                        name="endDate"
                                        ref={endRef}
                                        defaultValue=""
                                        className={`form-control ${errors.endDate ? 'is-invalid' : ''}`}
                                    />
                                    {errors.endDate && (
                                        <div className="invalid-feedback">{errors.endDate}</div>
                                    )}
                                </div>
                            </div>

                            <div className="d-flex gap-2">
                                <button type="submit" className="btn case-primary-btn">
                                    Create
                                </button>
                                <button
                                    type="button"
                                    className="btn btn-secondary"
                                    onClick={() => navigate('/project-dashboard')}
                                >
                                    Back
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </main>
        </div>
    );
}

export default CreateProjectForm;
