// filename: ProjectOwnerDashboard.jsx
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { useContext, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import { getProjectsByOwner } from '../services/projectService';
import {
    getAllIssues,
    ISSUE_STATUSES,
    normalizeIssueStatus,
    getIssuesByProject
} from '../services/issueService';
import {
    getAllUsers,
    getProfileFallback,
    getProfileImage
} from '../services/userService';

function ProjectOwnerDashboard() {
    const { user, isLoggedIn, ctxLogout } = useContext(AuthContext);
    const navigate = useNavigate();

    const [projects, setProjects] = useState([]);
    const [selectedProject, setSelectedProject] = useState(null);
    const [viewAll, setViewAll] = useState(false);
    const [issues, setIssues] = useState([]);
    const [createdIssueCount, setCreatedIssueCount] = useState(0);
    const [users, setUsers] = useState([]);
    const [searchText, setSearchText] = useState('');
    const [priority, setPriority] = useState('');
    const [assigneeId, setAssigneeId] = useState('');
    const [error, setError] = useState('');

    useEffect(() => {
        if (!isLoggedIn) {
            navigate('/login');
            return;
        }

        if (Number(user?.role) !== 1) {
            navigate('/assignee-dashboard');
            return;
        }

        const load = async () => {
            try {
                const [data, allIssues, userData] = await Promise.all([
                    getProjectsByOwner(user.userId),
                    getAllIssues(),
                    getAllUsers()
                ]);

                setUsers(userData);
                setProjects(data);

                setCreatedIssueCount(
                    allIssues.filter(
                        (issue) =>
                            Number(issue.createdBy) === Number(user.userId)
                    ).length
                );

                if (data.length > 0) {
                    setSelectedProject(data[0]);
                    const projectIssues = await getIssuesByProject(data[0].id);
                    setIssues(projectIssues);
                } else {
                    setSelectedProject(null);
                    setIssues([]);
                }
            } catch (err) {
                setError(
                    err.response?.data?.message ||
                    'Unable to load project dashboard.'
                );
            }
        };

        if (user?.userId) {
            load();
        }
    }, [isLoggedIn, navigate, user?.userId]);

    const selectProject = async (project) => {
        setViewAll(false);
        setSelectedProject(project);
        setError('');

        try {
            const data = await getIssuesByProject(project.id);
            setIssues(data);
        } catch (err) {
            setError(
                err.response?.data?.message ||
                'Unable to load project issues.'
            );
        }
    };

    const loadAllProjectIssues = async () => {
        setViewAll(true);
        setError('');

        try {
            const results = await Promise.all(
                projects.map((project) => getIssuesByProject(project.id))
            );
            setIssues(results.flat());
        } catch (err) {
            setError(
                err.response?.data?.message ||
                'Unable to load issues for all projects.'
            );
        }
    };

    const visibleIssues = useMemo(() => {
        let result = issues;

        if (priority) {
            result = result.filter(
                (issue) =>
                    String(issue.priority).toUpperCase() === priority
            );
        }

        if (assigneeId) {
            result = result.filter(
                (issue) => Number(issue.assignee) === Number(assigneeId)
            );
        }

        if (searchText.trim()) {
            try {
                const regex = new RegExp(searchText, 'i');
                result = result.filter(
                    (issue) =>
                        regex.test(issue.summary || '') ||
                        regex.test(issue.description || '')
                );
            } catch {
                result = [];
            }
        }

        return result;
    }, [assigneeId, issues, priority, searchText]);

    if (!isLoggedIn || Number(user?.role) !== 1) {
        return null;
    }

    return (
        <div className="case-dashboard">
            <aside className="case-sidebar">
                <div className="profile-block">
                    <img
                        src={getProfileImage(user) || getProfileFallback(user)}
                        alt={user.name}
                        className="profile-image"
                        onError={(event) => {
                            event.currentTarget.src = getProfileFallback(user);
                        }}
                    />
                    <h5>{user.name}</h5>
                    <small>{user.email}</small>
                </div>

                <div className="sidebar-stats">
                    <div>
                        <strong>{projects.length}</strong>
                        <span>Projects Created</span>
                    </div>
                    <div>
                        <strong>{issues.length}</strong>
                        <span>Issues Created</span>
                    </div>
                </div>

                <Link to="/project-dashboard" className="sidebar-link">
                    Project Dashboard
                </Link>
                <Link to="/create-project" className="sidebar-link">
                    Create Project
                </Link>
                <Link to="/create-issue" className="sidebar-link">
                    Create Issue
                </Link>

                <button
                    className="sidebar-logout"
                    onClick={() => {
                        ctxLogout();
                        navigate('/login');
                    }}
                >
                    Logout
                </button>
            </aside>

            <main className="case-main">
                <div className="case-header-row">
                    <input
                        className="form-control case-search"
                        placeholder="Search summary or description"
                        value={searchText}
                        onChange={(event) => setSearchText(event.target.value)}
                    />
                    <div className="case-app-name">Issue Tracking System</div>
                </div>

                {error && (
                    <div className="alert alert-danger mt-3">{error}</div>
                )}

                {projects.length === 0 ? (
                    <div className="empty-state">
                        <h4>No Projects Available</h4>
                        <Link to="/create-project" className="btn case-primary-btn">
                            Create Project
                        </Link>
                    </div>
                ) : (
                    selectedProject && (
                        <>
                            <h5 className="dashboard-heading">
                                Project Dashboard
                            </h5>

                            <div className="project-summary">
                                <div>
                                    <label htmlFor="projectSelect">
                                        Project Name
                                    </label>
                                    <select
                                        id="projectSelect"
                                        className="form-select"
                                        value={
                                            viewAll ? 'all' : selectedProject.id
                                        }
                                        onChange={(event) => {
                                            const value = event.target.value;

                                            if (value === 'all') {
                                                loadAllProjectIssues();
                                                return;
                                            }

                                            const project = projects.find(
                                                (item) =>
                                                    Number(item.id) ===
                                                    Number(value)
                                            );
                                            if (project) {
                                                selectProject(project);
                                            }
                                        }}
                                    >
                                        <option value="all">
                                            All Projects
                                        </option>
                                        {projects.map((project) => (
                                            <option
                                                key={project.id}
                                                value={project.id}
                                            >
                                                {project.projectName}
                                            </option>
                                        ))}
                                    </select>
                                </div>

                                <div>
                                    <strong>Project Owner Name:</strong>
                                    <span>{user.name}</span>
                                </div>

                                {viewAll ? (
                                    <div>
                                        <strong>Viewing:</strong>
                                        <span>
                                            {' '}
                                            All projects ({projects.length})
                                        </span>
                                    </div>
                                ) : (
                                    <div>
                                        <strong>Start Date:</strong>
                                        <span>
                                            {selectedProject.startDate || '-'}
                                            {' | End Date: '}
                                            {selectedProject.endDate || '-'}
                                        </span>
                                    </div>
                                )}

                                <div>
                                    <label htmlFor="assigneeFilter">
                                        Filter by Assignee
                                    </label>
                                    <select
                                        id="assigneeFilter"
                                        className="form-select"
                                        value={assigneeId}
                                        onChange={(event) =>
                                            setAssigneeId(event.target.value)
                                        }
                                    >
                                        <option value="">All</option>
                                        {users
                                            .filter(
                                                (item) => Number(item.role) === 0
                                            )
                                            .map((item) => (
                                                <option
                                                    key={item.userId}
                                                    value={item.userId}
                                                >
                                                    {item.name}
                                                </option>
                                            ))}
                                    </select>
                                </div>

                                <div>
                                    <label htmlFor="priorityFilter">
                                        Filter by Priority
                                    </label>
                                    <select
                                        id="priorityFilter"
                                        className="form-select"
                                        value={priority}
                                        onChange={(event) =>
                                            setPriority(event.target.value)
                                        }
                                    >
                                        <option value="">All</option>
                                        <option value="LOW">LOW</option>
                                        <option value="MEDIUM">MEDIUM</option>
                                        <option value="HIGH">HIGH</option>
                                    </select>
                                </div>
                            </div>

                            <div className="status-board">
                                {ISSUE_STATUSES.map((status) => {
                                    const statusIssues = visibleIssues.filter(
                                        (issue) =>
                                            normalizeIssueStatus(
                                                issue.status
                                            ) === status.value
                                    );

                                    return (
                                        <div
                                            className="status-column"
                                            key={status.value}
                                        >
                                            <h5>
                                                {status.label}
                                                <span className="status-count">
                                                    {statusIssues.length}
                                                </span>
                                            </h5>

                                            {statusIssues.map((issue) => {
                                                const assignee = users.find(
                                                    (item) =>
                                                        Number(item.userId) ===
                                                        Number(issue.assignee)
                                                );

                                                const imageUser = assignee || {
                                                    userId: issue.assignee,
                                                    name: 'Assignee',
                                                    email: ''
                                                };

                                                return (
                                                    <button
                                                        className="issue-card"
                                                        key={issue.id}
                                                        onClick={() =>
                                                            navigate(
                                                                `/issue/${issue.id}`
                                                            )
                                                        }
                                                    >
                                                        <strong>
                                                            #{issue.id}
                                                        </strong>
                                                        <span>
                                                            {issue.summary}
                                                        </span>
                                                        <small>
                                                            {issue.description}
                                                        </small>
                                                        <small>
                                                            {issue.createdOn ||
                                                                '-'}
                                                        </small>

                                                        <div className="issue-card-footer">
                                                            <div className="issue-assignee">
                                                                <img
                                                                    src={
                                                                        getProfileImage(
                                                                            imageUser
                                                                        ) ||
                                                                        getProfileFallback(
                                                                            imageUser
                                                                        )
                                                                    }
                                                                    alt={
                                                                        imageUser.name ||
                                                                        'Assignee'
                                                                    }
                                                                    onError={(
                                                                        event
                                                                    ) => {
                                                                        event.currentTarget.src =
                                                                            getProfileFallback(
                                                                                imageUser
                                                                            );
                                                                    }}
                                                                />
                                                                <span>
                                                                    {imageUser.name ||
                                                                        issue.assignee}
                                                                </span>
                                                            </div>

                                                            <em className="issue-priority">
                                                                {issue.priority}
                                                            </em>
                                                        </div>
                                                    </button>
                                                );
                                            })}
                                        </div>
                                    );
                                })}
                            </div>
                        </>
                    )
                )}
            </main>
        </div>
    );
}

export default ProjectOwnerDashboard;
